In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
%matplotlib inline

In [2]:
df = pd.read_csv("Classified Data")

In [3]:
df = pd.read_csv("Classified Data",index_col=0)

In [4]:
from sklearn.preprocessing import StandardScaler

In [5]:
scaler = StandardScaler()

In [6]:
scaler.fit(df.drop("TARGET CLASS", axis=1))

StandardScaler()

In [7]:
scaler_features = scaler.transform(df.drop("TARGET CLASS", axis=1))

In [8]:
scaler_features

array([[-0.12354188,  0.18590747, -0.91343069, ..., -1.48236813,
        -0.9497194 , -0.64331425],
       [-1.08483602, -0.43034845, -1.02531333, ..., -0.20224031,
        -1.82805088,  0.63675862],
       [-0.78870217,  0.33931821,  0.30151137, ...,  0.28570652,
        -0.68249379, -0.37784986],
       ...,
       [ 0.64177714, -0.51308341, -0.17920486, ..., -2.36249443,
        -0.81426092,  0.11159651],
       [ 0.46707241, -0.98278576, -1.46519359, ..., -0.03677699,
         0.40602453, -0.85567   ],
       [-0.38765353, -0.59589427, -1.4313981 , ..., -0.56778932,
         0.3369971 ,  0.01034996]])

In [9]:
df_feat = pd.DataFrame(scaler_features, columns=df.drop("TARGET CLASS", axis=1).columns)

In [10]:
df_feat

WTT       PTI       EQW       SBI       LQE       QWG       FDJ  \
0   -0.123542  0.185907 -0.913431  0.319629 -1.033637 -2.308375 -0.798951   
1   -1.084836 -0.430348 -1.025313  0.625388 -0.444847 -1.152706 -1.129797   
2   -0.788702  0.339318  0.301511  0.755873  2.031693 -0.870156  2.599818   
3    0.982841  1.060193 -0.621399  0.625299  0.452820 -0.267220  1.750208   
4    1.139275 -0.640392 -0.709819 -0.057175  0.822886 -0.936773  0.596782   
..        ...       ...       ...       ...       ...       ...       ...   
995  0.211653 -0.312490  0.065163 -0.259834  0.017567 -1.395721 -0.849486   
996 -1.292453 -0.616901  0.369613  0.482648  1.569891  1.273495  0.362784   
997  0.641777 -0.513083 -0.179205  1.022255 -0.539703 -0.229680 -2.261339   
998  0.467072 -0.982786 -1.465194 -0.071465  2.368666  0.001269 -0.422041   
999 -0.387654 -0.595894 -1.431398  0.512722 -0.402552 -2.026512 -0.726253   

          PJF       HQE       NXJ  
0   -1.482368 -0.949719 -0.643314  
1   -0.202240 -1.828051  0.636759  
2    0.285707 -0.682494 -0.377850  
3    1.066491  1.241325 -1.026987  
4   -1.472352  1.040772  0.276510  
..        ...       ...       ...  
995 -2.604264 -0.139347 -0.069602  
996 -1.242110 -0.679746  1.473448  
997 -2.362494 -0.814261  0.111597  
998 -0.036777  0.406025 -0.855670  
999 -0.567789  0.336997  0.010350  

[1000 rows x 10 columns]

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
x = df_feat

In [13]:
y = df['TARGET CLASS']

In [14]:
X_train, X_test, y_train, y_test = train_test_split(x,y, test_size=0.33, random_state=42)

In [15]:
from sklearn.neighbors import KNeighborsClassifier

In [16]:
knn = KNeighborsClassifier(n_neighbors=1)

In [17]:
knn.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=1)

In [18]:
pred = knn.predict(X_test)

In [19]:
pred

array([0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0,
       1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0,
       0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0,
       0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1,

In [20]:
from sklearn.metrics import classification_report, confusion_matrix

In [21]:
print(confusion_matrix(y_test, pred))

[[146   9]
 [ 11 164]]


In [82]:
print(classification_report(y_test,pred))

              precision    recall  f1-score   support

           0       0.93      0.94      0.94       155
           1       0.95      0.94      0.94       175

    accuracy                           0.94       330
   macro avg       0.94      0.94      0.94       330
weighted avg       0.94      0.94      0.94       330

